# Nowy format obiektowy dla każdego monitora osobno
wallpaper {
    monitor = eDP-1
    path = /home/j4cob/Pictures/Wallpapers/pokemon_wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-4
    path = /home/j4cob/Pictures/Wallpapers/pokemon_wallpaper.jpg
    fit_mode = cover
}

# Opcje globalne (zostają na zewnątrz bloków)
splash = false
ipc = true

